# The port frpc clients will connect to
bindPort = 7000

# Enable dashboard to monitor connections
webServer.addr = "0.0.0.0"
webServer.port = 7500

# Authentication token (must match in frpc)
auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"
