services:
  frps:
    container_name: frp--server
    image: snowdreamtech/frps:0.69.1@sha256:dd38562286af13efe67d9bc61631daa4e98af362b7c82ebc2db9073f0c4b2012
    command:
      - frps
      - -c
      - /etc/frp/frps.toml
    env_file:
      - ./services/frp/.env
    volumes:
      - ./services/frp/frps.toml:/etc/frp/frps.toml:ro
    ports:
      - "7000:7000"
      - "25565:25565"
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "8888:8888/tcp"
      - "8888:8888/udp"
      - "7881:7881"
      - "50100-50200:50100-50200/udp"
    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.frp-home.entrypoints=websecure"
      - "traefik.tcp.routers.frp-home.rule=HostSNIRegexp(`.*`)"
      - "traefik.tcp.routers.frp-home.tls.passthrough=true"
      - "traefik.tcp.routers.frp-home.service=frp-home"
      - "traefik.tcp.services.frp-home.loadbalancer.server.port=8443"
      - "traefik.tcp.services.frp-home.loadbalancer.serversTransport=frp@file"

      - "traefik.tcp.routers.frp-remote.entrypoints=websecure"
      - "traefik.tcp.routers.frp-remote.rule=HostSNIRegexp(`^.*remote\\.emdecloud\\.de.*`)"
      - "traefik.tcp.routers.frp-remote.tls.passthrough=true"
      - "traefik.tcp.routers.frp-remote.service=frp-remote"
      - "traefik.tcp.services.frp-remote.loadbalancer.server.port=9443"
      - "traefik.tcp.services.frp-remote.loadbalancer.serversTransport=frp@file"

      - "traefik.http.routers.frps-dashboard.rule=Host(`frps.vps.emdecloud.de`)"
      - "traefik.http.routers.frps-dashboard.entrypoints=websecure"
      - "traefik.http.routers.frps-dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.frps-dashboard.tls.domains[0].main=frps.vps.emdecloud.de"
      - "traefik.http.routers.frps-dashboard.service=frps-dashboard"
      - "traefik.http.routers.frps-dashboard.middlewares=authentik-forward-auth@file"
      - "traefik.http.services.frps-dashboard.loadbalancer.server.port=7500"
    restart: unless-stopped
    networks:
      - traefik

  traefik:
    container_name: traefik--server
    image: traefik:v3.7.5@sha256:e4d98158c01ad752fc1071d4e9573788747230d902cdde00a772516e692d07c9
    volumes:
      - ./services/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./services/traefik/middlewares.toml:/etc/traefik/dynamic/middlewares.toml:ro
      - ./services/traefik/transports.toml:/etc/traefik/dynamic/transports.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.vps.emdecloud.de`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.tls.domains[0].main=traefik.vps.emdecloud.de"
      - "traefik.http.routers.traefik.middlewares=authentik-forward-auth@file"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  uptime-kuma:
    container_name: uptime-kuma--app
    image: louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
    volumes:
      - uptime-kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`status.vps.emdecloud.de`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=myresolver"
      - "traefik.http.routers.uptime-kuma.tls.domains[0].main=status.vps.emdecloud.de"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    restart: unless-stopped
    networks:
      - traefik

  snowflake-proxy:
    container_name: snowflake-proxy--server
    image: containers.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake:v2.14.1@sha256:1ded2a9bbb5d67d41f3c11f6b392b8a2735964e7b070e1bcb1278fddf28f90a4
    network_mode: host
    # For a full list of Snowflake Proxy CLI parameters see
    # https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/tree/main/proxy?ref_type=heads#running-a-standalone-snowflake-proxy
    command: ["-ephemeral-ports-range", "30000:50000"]
    restart: unless-stopped

  authentik-outpost-infra:
    container_name: authentik--outpost-infra
    image: ghcr.io/goauthentik/proxy:2026.5.3@sha256:7b6b69cd3d266809890498bd2b74576d2303b6235c4a1e63a0c60d7078aa8302
    networks:
      - traefik
    environment:
      AUTHENTIK_HOST: https://auth.emdecloud.de
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: ${AUTHENTIK_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik-outpost-infra.rule=Host(`authentik-outpost-infra.vps.emdecloud.de`) && PathPrefix(`/outpost.goauthentik.io/`)"
      - "traefik.http.routers.authentik-outpost-infra.entrypoints=websecure"
      - "traefik.http.routers.authentik-outpost-infra.tls.certresolver=myresolver"
      - "traefik.http.routers.authentik-outpost-infra.tls.domains[0].main=authentik-outpost-infra.vps.emdecloud.de"
      - "traefik.http.routers.authentik-outpost-infra.service=authentik-outpost-infra"
      - "traefik.http.services.authentik-outpost-infra.loadbalancer.server.port=9000"
    restart: unless-stopped

  alloy:
    container_name: grafana--alloy
    image: grafana/alloy:v1.17.0@sha256:1f370747567b3aec7850ff9e0b22c27dde6366c5cea53a08832a524cef4383f1
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/journal:/var/log/journal:ro
      - /:/rootsfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./services/alloy:/etc/alloy:ro"
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
      - --disable-reporting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy.rule=Host(`alloy.vps.emdecloud.de`)"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.tls.certresolver=myresolver"
      - "traefik.http.routers.alloy.tls.domains[0].main=alloy.vps.emdecloud.de"
      - "traefik.http.routers.alloy.middlewares=authentik-forward-auth@file"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"

networks:
  traefik:
    name: traefik
    enable_ipv6: true

volumes:
  uptime-kuma-data:
    name: uptime-kuma-data
    external: true # volume already exists
  traefik-certs:
    name: traefik-certs
    external: true # volume already exists
