[global]
checkNewVersion = false
sendAnonymousUsage = false

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"
allowACMEByPass = true

[entryPoints.websecure.transport.respondingTimeouts]
readTimeout = "600s"
idleTimeout = "600s"
writeTimeout = "600s"

[certificatesResolvers]
[certificatesResolvers.myresolver.acme]
email = "matthias@emdemail.de"
storage = "/certs/acme.json"

[certificatesResolvers.myresolver.acme.tlsChallenge]

[providers.docker]
exposedByDefault = false
network = "traefik"

[api]
dashboard = true
insecure = true

################################################################
# Load configurations from middleware.toml
################################################################
[providers.file]
directory = "/etc/traefik/dynamic"
watch = true
